obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.276, -0.1485], [0.31, 0], [0.276, 0.1485], [-0.276, 0.1485], [-0.276, -0.1485]]
#robot_radius: ir_of_robot
inflation_radius: 0.20
transform_tolerance: 0.5
map_update_rate: 4

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
